//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixBugtracker.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixBugtracker.BL.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added a comment to report &quot;{1}&quot;: &quot;{2}&quot;.
        /// </summary>
        internal static string CommentAddedNotification {
            get {
                return ResourceManager.GetString("CommentAddedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification from bugtracker.
        /// </summary>
        internal static string Email_DefaultSubject {
            get {
                return ResourceManager.GetString("Email_DefaultSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string Email_PasswordReset {
            get {
                return ResourceManager.GetString("Email_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invite to test a product.
        /// </summary>
        internal static string Email_ProductInvitation {
            get {
                return ResourceManager.GetString("Email_ProductInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to test product accepted.
        /// </summary>
        internal static string Email_ProductJoinAccepted {
            get {
                return ResourceManager.GetString("Email_ProductJoinAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing the product finished.
        /// </summary>
        internal static string Email_ProductTestingFinished {
            get {
                return ResourceManager.GetString("Email_ProductTestingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New comment to your report.
        /// </summary>
        internal static string Email_ReportCommentAdded {
            get {
                return ResourceManager.GetString("Email_ReportCommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your role changed.
        /// </summary>
        internal static string Email_RoleChanged {
            get {
                return ResourceManager.GetString("Email_RoleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm registration.
        /// </summary>
        internal static string Email_UserRegistrationSubject {
            get {
                return ResourceManager.GetString("Email_UserRegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}!&lt;br&gt;Your confirmation code for registration on bugtracker: {1}.
        /// </summary>
        internal static string Email_UserRegistrationText {
            get {
                return ResourceManager.GetString("Email_UserRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}!&lt;br&gt;&lt;br&gt;{1}.
        /// </summary>
        internal static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string Moderator {
            get {
                return ResourceManager.GetString("Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to test product &quot;{0}&quot;..
        /// </summary>
        internal static string ProductInviteRequest {
            get {
                return ResourceManager.GetString("ProductInviteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request to test product &quot;{0}&quot; has been accepted..
        /// </summary>
        internal static string ProductJoinRequestAccepted {
            get {
                return ResourceManager.GetString("ProductJoinRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of product &quot;{0}&quot; is finished..
        /// </summary>
        internal static string ProductTestingFinished {
            get {
                return ResourceManager.GetString("ProductTestingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the severity of report &quot;{1}&quot; to &quot;{2}&quot;.
        /// </summary>
        internal static string ReportSeverityChanged {
            get {
                return ResourceManager.GetString("ReportSeverityChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the severity of report &quot;{1}&quot; to &quot;{2}&quot;: &quot;{3}&quot;.
        /// </summary>
        internal static string ReportSeverityChangedWithComment {
            get {
                return ResourceManager.GetString("ReportSeverityChangedWithComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the status of report &quot;{1}&quot; to &quot;{2}&quot;.
        /// </summary>
        internal static string ReportStatusChanged {
            get {
                return ResourceManager.GetString("ReportStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the status of report &quot;{1}&quot; to &quot;{2}&quot;: &quot;{3}&quot;.
        /// </summary>
        internal static string ReportStatusChangedWithComment {
            get {
                return ResourceManager.GetString("ReportStatusChangedWithComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your role changed to {0}.
        /// </summary>
        internal static string RoleChangedNotification {
            get {
                return ResourceManager.GetString("RoleChangedNotification", resourceCulture);
            }
        }
    }
}
