//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixBugtracker.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixBugtracker.BL.Resources.EnumValues", typeof(EnumValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ProductAccessLevel_Closed {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ProductAccessLevel_Open {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        internal static string ProductAccessLevel_Secret {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App for phones/tablets.
        /// </summary>
        internal static string ProductType_MobileApp {
            get {
                return ResourceManager.GetString("ProductType_MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ProductType_Other {
            get {
                return ResourceManager.GetString("ProductType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App for desktop PCs.
        /// </summary>
        internal static string ProductType_PCApp {
            get {
                return ResourceManager.GetString("ProductType_PCApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        internal static string ProductType_WebSite {
            get {
                return ResourceManager.GetString("ProductType_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Role_Employee {
            get {
                return ResourceManager.GetString("Role_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string Role_Moderator {
            get {
                return ResourceManager.GetString("Role_Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string Role_Tester {
            get {
                return ResourceManager.GetString("Role_Tester", resourceCulture);
            }
        }
    }
}
