//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixBugtracker.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixBugtracker.BL.Resources.EnumValues", typeof(EnumValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string ProductAccessLevel_Closed {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ProductAccessLevel_Open {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        internal static string ProductAccessLevel_Secret {
            get {
                return ResourceManager.GetString("ProductAccessLevel_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App for phones/tablets.
        /// </summary>
        internal static string ProductType_MobileApp {
            get {
                return ResourceManager.GetString("ProductType_MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string ProductType_Other {
            get {
                return ResourceManager.GetString("ProductType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App for desktop PCs.
        /// </summary>
        internal static string ProductType_PCApp {
            get {
                return ResourceManager.GetString("ProductType_PCApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        internal static string ProductType_WebSite {
            get {
                return ResourceManager.GetString("ProductType_WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aestetic discrepancies.
        /// </summary>
        internal static string ReportProblemType_AesteticDiscrepancies {
            get {
                return ResourceManager.GetString("ReportProblemType_AesteticDiscrepancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App crash.
        /// </summary>
        internal static string ReportProblemType_AppCrash {
            get {
                return ResourceManager.GetString("ReportProblemType_AppCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App froze.
        /// </summary>
        internal static string ReportProblemType_AppFroze {
            get {
                return ResourceManager.GetString("ReportProblemType_AppFroze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data damage.
        /// </summary>
        internal static string ReportProblemType_DataDamage {
            get {
                return ResourceManager.GetString("ReportProblemType_DataDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function not working.
        /// </summary>
        internal static string ReportProblemType_FunctionNotWorking {
            get {
                return ResourceManager.GetString("ReportProblemType_FunctionNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string ReportProblemType_Performance {
            get {
                return ResourceManager.GetString("ReportProblemType_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string ReportProblemType_Suggestion {
            get {
                return ResourceManager.GetString("ReportProblemType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typo.
        /// </summary>
        internal static string ReportProblemType_Typo {
            get {
                return ResourceManager.GetString("ReportProblemType_Typo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string ReportSeverity_Critical {
            get {
                return ResourceManager.GetString("ReportSeverity_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ReportSeverity_High {
            get {
                return ResourceManager.GetString("ReportSeverity_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string ReportSeverity_Low {
            get {
                return ResourceManager.GetString("ReportSeverity_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string ReportSeverity_Medium {
            get {
                return ResourceManager.GetString("ReportSeverity_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerability.
        /// </summary>
        internal static string ReportSeverity_Vulnerability {
            get {
                return ResourceManager.GetString("ReportSeverity_Vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string ReportStatus_Blocked {
            get {
                return ResourceManager.GetString("ReportStatus_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reproduce.
        /// </summary>
        internal static string ReportStatus_CannotReproduce {
            get {
                return ResourceManager.GetString("ReportStatus_CannotReproduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string ReportStatus_Declined {
            get {
                return ResourceManager.GetString("ReportStatus_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred.
        /// </summary>
        internal static string ReportStatus_Deferred {
            get {
                return ResourceManager.GetString("ReportStatus_Deferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string ReportStatus_Duplicate {
            get {
                return ResourceManager.GetString("ReportStatus_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        internal static string ReportStatus_Fixed {
            get {
                return ResourceManager.GetString("ReportStatus_Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string ReportStatus_InProgress {
            get {
                return ResourceManager.GetString("ReportStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs correction.
        /// </summary>
        internal static string ReportStatus_NeedsCorrection {
            get {
                return ResourceManager.GetString("ReportStatus_NeedsCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ReportStatus_Open {
            get {
                return ResourceManager.GetString("ReportStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        internal static string ReportStatus_Outdated {
            get {
                return ResourceManager.GetString("ReportStatus_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for testing.
        /// </summary>
        internal static string ReportStatus_ReadyForTesting {
            get {
                return ResourceManager.GetString("ReportStatus_ReadyForTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopened.
        /// </summary>
        internal static string ReportStatus_Reopened {
            get {
                return ResourceManager.GetString("ReportStatus_Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under review.
        /// </summary>
        internal static string ReportStatus_UnderReview {
            get {
                return ResourceManager.GetString("ReportStatus_UnderReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        internal static string ReportStatus_Verified {
            get {
                return ResourceManager.GetString("ReportStatus_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won&apos;t be fixed.
        /// </summary>
        internal static string ReportStatus_WontBeFixed {
            get {
                return ResourceManager.GetString("ReportStatus_WontBeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Role_Employee {
            get {
                return ResourceManager.GetString("Role_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string Role_Moderator {
            get {
                return ResourceManager.GetString("Role_Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string Role_Tester {
            get {
                return ResourceManager.GetString("Role_Tester", resourceCulture);
            }
        }
    }
}
