//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixBugtracker.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixBugtracker.BL.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not confirmed.
        /// </summary>
        public static string AccountNotConfirmed {
            get {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All submitted tags already exist.
        /// </summary>
        public static string AllTagsAlreadyExist {
            get {
                return ResourceManager.GetString("AllTagsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A producth with requested name already exist.
        /// </summary>
        public static string AlreadyHaveProductWithName {
            get {
                return ResourceManager.GetString("AlreadyHaveProductWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated user not found or deleted.
        /// </summary>
        public static string AuthUserNotFound {
            get {
                return ResourceManager.GetString("AuthUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change a role for requested user.
        /// </summary>
        public static string CannotChangeRole {
            get {
                return ResourceManager.GetString("CannotChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change your role.
        /// </summary>
        public static string CannotRevokeAdminRoleFromCurrentUser {
            get {
                return ResourceManager.GetString("CannotRevokeAdminRoleFromCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion not allowed after 24 hours.
        /// </summary>
        public static string DeletionTimeRestriction {
            get {
                return ResourceManager.GetString("DeletionTimeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing not allowed after 24 hours.
        /// </summary>
        public static string EditTimeRestriction {
            get {
                return ResourceManager.GetString("EditTimeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail is already in use.
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with this id is not an image.
        /// </summary>
        public static string FileIsNotImage {
            get {
                return ResourceManager.GetString("FileIsNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this file denied.
        /// </summary>
        public static string ForbiddenFile {
            get {
                return ResourceManager.GetString("ForbiddenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to these files ({0}) denied.
        /// </summary>
        public static string ForbiddenFiles {
            get {
                return ResourceManager.GetString("ForbiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to product denied.
        /// </summary>
        public static string ForbiddenProduct {
            get {
                return ResourceManager.GetString("ForbiddenProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a comment with severity or status update is not allowed.
        /// </summary>
        public static string ForbiddenSeverityStatusCommentDeletion {
            get {
                return ResourceManager.GetString("ForbiddenSeverityStatusCommentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid comment id.
        /// </summary>
        public static string InvalidCommentId {
            get {
                return ResourceManager.GetString("InvalidCommentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong confirmation code.
        /// </summary>
        public static string InvalidConfirmationCode {
            get {
                return ResourceManager.GetString("InvalidConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid creator id.
        /// </summary>
        public static string InvalidCreatorId {
            get {
                return ResourceManager.GetString("InvalidCreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value. Must be {0}.
        /// </summary>
        public static string InvalidEnum {
            get {
                return ResourceManager.GetString("InvalidEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of uploaded file is wrong.
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the parameters specified was invalid.
        /// </summary>
        public static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product id.
        /// </summary>
        public static string InvalidProductId {
            get {
                return ResourceManager.GetString("InvalidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid report id.
        /// </summary>
        public static string InvalidReportId {
            get {
                return ResourceManager.GetString("InvalidReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file was not found.
        /// </summary>
        public static string NotFoundFile {
            get {
                return ResourceManager.GetString("NotFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested files ({0}) not found.
        /// </summary>
        public static string NotFoundFiles {
            get {
                return ResourceManager.GetString("NotFoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested product was not found.
        /// </summary>
        public static string NotFoundProduct {
            get {
                return ResourceManager.GetString("NotFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the specified tags are not found or archived.
        /// </summary>
        public static string NotFoundSomeTags {
            get {
                return ResourceManager.GetString("NotFoundSomeTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user was not found.
        /// </summary>
        public static string NotFoundUser {
            get {
                return ResourceManager.GetString("NotFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already read all notifications.
        /// </summary>
        public static string NotificationAlreadyRead {
            get {
                return ResourceManager.GetString("NotificationAlreadyRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invitation to test this product has already been sent to the requested user.
        /// </summary>
        public static string ProductInviteAlreadySent {
            get {
                return ResourceManager.GetString("ProductInviteAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing of this product is over.
        /// </summary>
        public static string ProductTestingIsOver {
            get {
                return ResourceManager.GetString("ProductTestingIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is expired.
        /// </summary>
        public static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to edit report.
        /// </summary>
        public static string ReportEditForbidden {
            get {
                return ResourceManager.GetString("ReportEditForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already has this role.
        /// </summary>
        public static string RoleIsSame {
            get {
                return ResourceManager.GetString("RoleIsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment required for this status.
        /// </summary>
        public static string StatusRequiredComment {
            get {
                return ResourceManager.GetString("StatusRequiredComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} is empty.
        /// </summary>
        public static string TagIsEmpty {
            get {
                return ResourceManager.GetString("TagIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} is long.
        /// </summary>
        public static string TagIsLong {
            get {
                return ResourceManager.GetString("TagIsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too short.
        /// </summary>
        public static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many files.
        /// </summary>
        public static string TooManyFiles {
            get {
                return ResourceManager.GetString("TooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too long.
        /// </summary>
        public static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user is already a member of this product.
        /// </summary>
        public static string UserAlreadyMember {
            get {
                return ResourceManager.GetString("UserAlreadyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user is not a member of this product.
        /// </summary>
        public static string UserIsNotMember {
            get {
                return ResourceManager.GetString("UserIsNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or password is incorrect.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
    }
}
